In [7]:
#knapsack: bagweight và n thì bagweight là ngang
#cuttingrod: j là độ dài cuộn dây cho phép cũng là ngang
#special coinChange: money cho phép lại nằm dọc 
#table[0][i] = 1 để khi tính x i - moneyList[j] = 0 là còn trường hợp tờ tiền là chính nó không đổi -> + 1
#-------------------------------------------------------------------------------------------
#trong mỗi vòng lặp
# --> x là trường hợp tính cả tờ tiền thứ j
# --> y là trường hợp không tính tờ tiền đó
#ví dụ là ô đổi 5K bằng các tờ 1, 2, 3K đã tính được ở trên.
#x = trường hợp đổi tờ 2K bằng các tờ 1, 2, 3(có dùng tờ 3 nên sẽ là đổi tờ(5 - 3) bằng 1 2 3)
#y = trường hợp đổi tờ 5K bằng các tờ 1, 2

In [8]:
import numpy as np
def coinChange(moneyList, length, money):
    table = [[0 for x in range(length)] for x in range(money + 1)]
    for i in range(length):
        table[0][i] = 1
    
    for i in range(1, money + 1):
        for j in range(length):
            x = table[i - moneyList[j]][j] if i >= moneyList[j] else 0
            y = table[i][j - 1] if j >= 1 else 0
            table[i][j] = x + y
    table = np.array(table)
    return table#[money][length - 1]
moneyList = [x for x in range(1, 11)]
length = len(moneyList)
money = 10
print(f"Số cách đổi là: {coinChange(moneyList, length, money)}")

Số cách đổi là: [[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  2  2  2  2  2  2  2  2  2]
 [ 1  2  3  3  3  3  3  3  3  3]
 [ 1  3  4  5  5  5  5  5  5  5]
 [ 1  3  5  6  7  7  7  7  7  7]
 [ 1  4  7  9 10 11 11 11 11 11]
 [ 1  4  8 11 13 14 15 15 15 15]
 [ 1  5 10 15 18 20 21 22 22 22]
 [ 1  5 12 18 23 26 28 29 30 30]
 [ 1  6 14 23 30 35 38 40 41 42]]
