In [6]:
import numpy as np
def solve(board, n):
    def counting(board, i, j, n):
        #ham dem so hang xom
        number = 0
        for a in range(i - 1, i + 2):
            for b in range(j - 1, j + 2):
                if a >= 0 and a <= n - 1 and b >= 0 and b <= n - 1:
                    if a!=i or b!=j:
                        if board[a][b] == 1:
                            number += 1
        return number
    neightbor = [[0 for _ in range(n)] for _ in range(n)]
    #neightbor nxn dem so hang xom de khong cap nhat vao bang
    for a in range(n):
        for b in range(n):
            neightbor[a][b] = counting(board, a, b, n)
    #!!!!!!!! solve
    for q in range(1, n - 1):
        for w in range(1, n - 1):
            if board[q][w] == 1 and neightbor[q][w] < 2:
                board[q][w] = 0
            elif board[q][w] == 1 and neightbor[q][w] == 2:
                board[q][w] = 1
            elif board[q][w] == 1 and neightbor[q][w] == 3:
                board[q][w] = 1
            elif board[q][w] == 1 and neightbor[q][w] > 3:
                board[q][w] = 0
            elif board[q][w] == 0 and neightbor[q][w] == 3:
                board[q][w] = 1
            elif board[q][w] == 0:
                board[q][w] = 0
    return board
board = [[0,0,0,0,0],
        [0,1,1,0,0],
        [0,1,1,0,0],
        [0,1,1,0,0],
        [0,0,0,0,0]]
npboard = np.array(board)
n = len(board[0])
print("Question: ")
print(npboard)
print("Key: ")
print(solve(npboard, n))


Question: 
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 1 1 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
Key: 
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
